FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -yq qemu-utils libguestfs-tools

COPY ./balena-image-flasher-unwrap /bin
RUN chmod a+x /bin/balena-image-flasher-unwrap

CMD /bin/balena-image-flasher-unwrap
