#!/bin/bash

set -e

mountpoints=/tmp/resin-image-flasher-unwrap/mountpoints
resin_image_boot_mnt=${mountpoints}/resin-boot
resin_image_root_mnt=${mountpoints}/resin-root
resin_image_flasher_boot_mnt=${mountpoints}/flash-boot
resin_image_flasher_root_mnt=${mountpoints}/flash-root

help() {
	cat << EOF
$0 <OPTION>

	Options:
		-f, --resin-image-flasher
			The file to be used as a flasher image.
			This argument is mandatory.
		-o, --output-directory
			By default the unwrapped image will be outputted in the directory
			where this tool resides. Custom location can be specified using
			this flag.
EOF
}

function log {
	case $1 in
		ERROR)
			loglevel=ERROR
			shift
			;;
		WARN)
			loglevel=WARNING
			shift
			;;
		*)
		loglevel=LOG
			;;
	esac
	printf "%s%s\n" "[$loglevel]" "$1"
	if [ "$loglevel" == "ERROR" ]; then
		exit 1
	fi
}

# Parse auguments
while [[ $# -gt 0 ]]; do
	arg="$1"
	case $arg in
		-h|--help)
			help
			exit 0
			;;
		-f|--resin-image-flasher)
			if [ -z "$2" ]; then
				log ERROR "\"$1\" argument needs a value."
			fi
			resin_image_flasher=$2
			shift
			;;
		-o|--output-directory)
			if [ -z "$2" ]; then
				log ERROR "\"$1\" argument needs a value."
			fi
			OUTPUT_DIR=$2
			shift
			;;
		*)
			echo "Unrecognized option $1."
			help
			exit 1
			;;
	esac
	shift
done

cleanup () {
	EXIT_CODE=$?
	umount "$resin_image_boot_mnt" > /dev/null 2>&1 || true
	umount "$resin_image_root_mnt" > /dev/null 2>&1 || true
	umount "$resin_image_flasher_boot_mnt" > /dev/null 2>&1 || true
	umount "$resin_image_flasher_root_mnt" > /dev/null 2>&1 || true
	losetup -d "$resin_image_loop_dev" "$resin_image_flasher_loop_dev" > /dev/null 2>&1 || true
	exit $EXIT_CODE
}
trap cleanup EXIT SIGHUP SIGINT SIGTERM

# Get the absolute script location
pushd "$(dirname "$0")" > /dev/null 2>&1
SCRIPTPATH="$(pwd)"
popd > /dev/null 2>&1

# By default output the image in the same directory as this tool
[ -z "$OUTPUT_DIR" ] && OUTPUT_DIR=$SCRIPTPATH
[ ! -d "$OUTPUT_DIR" ] && log ERROR "Output directory not found."

# Setup mountpoints
rm -rvf $mountpoints
mkdir -p \
	$resin_image_boot_mnt \
	$resin_image_root_mnt \
	$resin_image_flasher_boot_mnt \
	$resin_image_flasher_root_mnt

[ -z "$resin_image_flasher" ] && log ERROR "No resin image flasher available."
log "Unwraping resin image from the provided resin image flasher..."
resin_image_flasher_loop_dev="$(losetup -fP --show "$resin_image_flasher")"
mount "${resin_image_flasher_loop_dev}p1" "$resin_image_flasher_boot_mnt" > /dev/null 2>&1
mount "${resin_image_flasher_loop_dev}p2" "$resin_image_flasher_root_mnt" > /dev/null 2>&1
resin_image="$(find "$resin_image_flasher_root_mnt/opt" -type f | head -n1)"
[ -z "$resin_image" ] && log ERROR "The resin image flasher doesn't contain a resin image."
cp "$resin_image" "$OUTPUT_DIR/resin-image.img"
resin_image="$OUTPUT_DIR/resin-image.img"

log "Migrating configurationg from resin image flasher to resin-image..."
resin_image_loop_dev="$(losetup -fP --show "$resin_image")"
mount "${resin_image_loop_dev}p1" "$resin_image_boot_mnt"
mount "${resin_image_loop_dev}p2" "$resin_image_root_mnt"
cp -r $resin_image_flasher_boot_mnt/splash/* "$resin_image_boot_mnt/splash"
cp "$resin_image_flasher_boot_mnt/config.json" "$resin_image_boot_mnt/config.json"
if [ -d  "$resin_image_flasher_boot_mnt/system-connections" ]; then
	rm -rf "$resin_image_boot_mnt/system-connections"
	cp -r "$resin_image_flasher_boot_mnt/system-connections" "$resin_image_boot_mnt/system-connections"
fi
if [ -d  "$resin_image_flasher_boot_mnt/system-proxy" ]; then
	rm -rf "$resin_image_boot_mnt/system-proxy"
	cp -r "$resin_image_flasher_boot_mnt/system-proxy" "$resin_image_boot_mnt/system-proxy"
fi

log "Done."
